services:
  matomo:
    image: matomo:latest
    container_name: ${MATOMO_CONTAINER_NAME}
    restart: always
    ports:
      - "${MATOMO_PORT}:80"
    volumes:
      - ${MATOMO_DATA_PATH}:/var/www/html
    environment:
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: ${MATOMO_TABLES_PREFIX:-matomo_}
      MATOMO_DATABASE_DBNAME: ${MYSQL_DATABASE}
      MATOMO_DATABASE_USERNAME: ${MYSQL_USER}
      MATOMO_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - matomo_network

  db:
    image: mariadb:latest
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - matomo_network

networks:
  matomo_network:
    name: ${NETWORK_NAME}
    driver: bridge